matrice<-cor(data[,c(10:30)],use="pairwise",method="spearman")
round(matrice,2)
library(corrplot)
corrplot(matrice, method="circle")
boxplot(data[,10:30])
library(outliers)
grubbs.test(data$item6)
library(psych)
corr.test(data[,10:30],method="spearman", use="pairwise")
KMO(data[,10:30])
cortest.bartlett(data[,10:30])
fa.parallel(dataf[,10:30],fa="fa",fm="pa")
dataf<-data[,-15]
library(GPArotation)
fa(data[,10:30],nfactors = 3, rotate = "oblimin",fm="pa",use="pairwise")
alpha(data[,14:16])
